# Generated by Django 5.2 on 2025-04-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                default="nobrand",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="store.brand",
            ),
        ),
    ]
